# Generated by Django 3.0.5 on 2020-04-29 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        ('babies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.Parent'),
        ),
    ]
